drop table if exists member CASCADE;
create table member (
    id   varchar(40) generated by default as identity,
    name varchar(255),
    primary key (id)
);
select * from member;
insert into member (id, name) values ('asdsad', 'dasdsaasd');